### ISSUE TITLE
ErrorMiddleware needs Meteor.bindEnvironment

### ISSUE THREAD

**Issue by imajus** [stubailo/meteor-rest#121]
Here's what error I get when I use ErrorMiddleware:

```
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at Object.Meteor.bindEnvironment (packages/meteor/dynamics_nodejs.js:85:1)
    at Object.handle (packages/simple_json-routes/json-routes.js:46:1)
    at next (…/npm/node_modules/connect/lib/proto.js:169:17)
    at Immediate.next (…/npm/node_modules/connect/lib/proto.js:171:11)
    at Immediate.immediate._onImmediate (timers.js:435:18)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by stubailo** [comment]
Can you provide an example of your middleware?

**Comment by imajus** [comment]
I'm using the example from the doc:

```
JsonRoutes.ErrorMiddleware.use(RestMiddleware.handleErrorAsJson);
```

When I comment out this line, the errors handle normally but displayed as HTML not JSON.

**Comment by oulp** [comment]
I'm using
`request.headers['ticket']`
also got the error 
`Error: Can't wait without a fiber`

**Comment by zeroasterisk** [comment]
I've been seeing this too, recently, but I have yet to investigate and create a test case for it...

Currently, only in production bundled code.

```
$ meteor --version; node --version; npm --version
Meteor 1.4.1.1
v4.4.7
3.10.7
```

**Comment by shawnmclean** [comment]
This isn't only happening in ErrorMiddleware, also just regular `JsonRoutes.Middleware.use()`. I have a `Collection.findOne()` inside one of these middlewares that is complaining.

```
$ meteor --version
Meteor 1.4.1.1
$ meteor node --version
v4.5.0
$ npm --version
3.10.7
$ node --version 
v6.5.0
```

**Comment by shawnmclean** [comment]
My middleware looks like this:

```
import URL from 'url-parse'
import { Settings } from '/imports/api/collections/Settings'

export default function authenticateApiByToken(req, res, next) {
    const appId = getAppIdFromAuthToken(req.authToken)
    // ... rest of logic
    next()
}

function getAppIdFromAuthToken(token) {
    if (!token) {
        return null
    }

    var settings = Settings.findOne()
    if(settings && settings.apiKey == token){
        return true
    }

    return null
}
```

Error occurs at `var settings = Settings.findOne()`

**Comment by shawnmclean** [comment]
I've been trying to fix this issue. I cannot drill deeper into the stack trace because meteor does not allow me to pass in a stack trace limit to node. Does anyone have any other idea how I can help dig into this issue?

I've tried brand new projects and its the same thing.

**Comment by holmrenser** [comment]
I am running into this exact same problem when trying to use simple:rest-accounts-password. If I'm correct I should be able to approach my like this: 
```
curl -H "Content-Type: application/json" -d "{username:admin,password:admin}" http://localhost:3000/users/login
```

This is resulting in the errors described above.

**Comment by Ethaan** [comment]
@shawnmclean did you find a fix for this?

**Comment by shawnmclean** [comment]
@Ethaan Nope, I ended up moving away from meteor because of this. Had to build a sort of microservice to do REST operations initially.
