### ISSUE TITLE
Package should use `DDP._CurrentInvocation` before calling methods?

### ISSUE THREAD

**Issue by dotansimha** [stubailo/meteor-rest#133]
Hi @stubailo ,

I am trying to figure out an issue I have with this package: I have a server side only method, that uses `Meteor.userId()` - when calling from DDP it works, but when calling with REST, I get the following error:
```
W20170510-07:20:29.605(3)? (STDERR) Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
W20170510-07:20:29.606(3)? (STDERR)     at AccountsServer.userId (packages/accounts-base/accounts_server.js:82:13)
W20170510-07:20:29.607(3)? (STDERR)     at AccountsServer.user (packages/accounts-base/accounts_common.js:58:23)
W20170510-07:20:29.607(3)? (STDERR)     at Object.Meteor.user (packages/accounts-base/accounts_common.js:261:19)
W20170510-07:20:29.608(3)? (STDERR)     at server/methods/methods.js:494:37
W20170510-07:20:29.608(3)? (STDERR)     at Object.validate (server/methods/methods.js:334:25)
W20170510-07:20:29.609(3)? (STDERR)     at packages/simple_rest.js:385:33
W20170510-07:20:29.609(3)? (STDERR)     at packages/simple_json-routes.js:98:9
```

The error is thrown from `AccountsServer` ([here](https://github.com/meteor/meteor/blob/6a9f8b904425efce112103f3846d7a153f8988ca/packages/accounts-base/accounts_server.js#L80-L84)) and caused by the fact that `DDP._CurrentInvocation.get()` is not set before the actual call to the Meteor method.

Digging inside this package's code and Meteor's method invocation code, I noticed that before calling the actual server method, Meteor sets the `DDP._CurrentInvocation.withValue` to the method invocation ([here](https://github.com/meteor/meteor/blob/master/packages/ddp-server/livedata_server.js#L717)).

I changed this package's code and tested it locally, the `methodInvocation` is now a `DDPCommon.MethodInvocation` object, and before calling the actual handler - the `DDP._CurrentInvocation.withValue` is called.

@stubailo what do you think? I that a valid solution? If so, I'll open a PR for that.

**Comment by dotansimha** [comment]
Just found out this one: https://github.com/stubailo/meteor-rest/pull/118/files 

👍
