### ISSUE TITLE
using numtel:mysql with simple:rest

### ISSUE THREAD

**Issue by juliuscarvajal** [stubailo/meteor-rest#60]
Great stuff with this simple:rest package. Thank you very much.
Anybody else tried using numtel:mysql with this package?

I am using it but I'm getting stuck with the following errors:
```
I20150921-16:08:50.683(10)? Internal server error in publications/locations [TypeError: Object #<LiveMysqlSelect> has no method 'fetch'] TypeError: Object #<LiveMysqlSelect> has no method 'fetch'
I20150921-16:08:50.685(10)?     at httpPublishCursor (packages/simple:rest/rest.js:161:1)
I20150921-16:08:50.685(10)?     at packages/simple:rest/rest.js:44:1
I20150921-16:08:50.685(10)?     at catchAndReportErrors (packages/simple:rest/rest.js:241:1)
I20150921-16:08:50.685(10)?     at packages/simple:rest/rest.js:25:1
I20150921-16:08:50.685(10)?     at packages/simple:json-routes/json-routes.js:45:1
```
Any ideas?

The (redacted) code below:
```
Locations = new MysqlSubscription('locations');

var liveDb = new LiveMysql({
/*...*/
});

Meteor.publish('locations', function () {
  return liveDb.select(
    'select * from channel', [{
      table: 'channel'
    }]
  );
});
```

**Comment by stubailo** [comment]
Sounds like numtel:mysql needs to add support for the `fetch` method?

**Comment by juliuscarvajal** [comment]
Thanks for the quick reply, mate. Will head over to numtel:mysql.
