### ISSUE TITLE
missing check in meteor 1.2+

### ISSUE THREAD

**Issue by dotnetwise** [stubailo/meteor-rest#70]
```
I20151115-21:05:25.011(1)? Internal server error in publications/api-routes [ReferenceError: check is not defined] ReferenceError: check is not defined
I20151115-21:05:25.012(1)?     at [object Object]._.extend.added (packages/simple_rest/packages/simple_rest.js:51:1)
I20151115-21:05:25.012(1)?     at Package (packages/simple_rest/packages/simple_rest.js:437:1)
I20151115-21:05:25.013(1)?     at Function._.each._.forEach (packages/underscore/packages/underscore.js:142:1)
I20151115-21:05:25.013(1)?     at [object Object].Package (packages/simple_rest/packages/simple_rest.js:436:1)
I20151115-21:05:25.013(1)?     at Meteor.publish (packages/simple_rest/packages/simple_rest.js:170:1)
I20151115-21:05:25.013(1)?     at catchAndReportErrors (packages/simple_rest/packages/simple_rest.js:372:1)
I20151115-21:05:25.014(1)?     at Meteor.publish (packages/simple_rest/packages/simple_rest.js:156:1)
I20151115-21:05:25.014(1)?     at JsonRoutes.add (packages/simple_json-routes/packages/simple_json-routes.js:53:1)
```

It worked after I manually added
```js
meteor add check
```

**Comment by dotnetwise** [comment]
Pull request https://github.com/stubailo/meteor-rest/pull/63 fixes #70 and #62
