### ISSUE TITLE
Meteor 1.2.1 fails with object has no method `apply`

### ISSUE THREAD

**Issue by dotnetwise** [stubailo/meteor-rest#71]
Both server and client side:
```js
agency = new Meteor.Collection("agency");
```

Server side:
```js
Meteor.publish('agency', {
    httpMethod: 'get',
});
```
Accessing http://localhost:3000/publications/agency fails with this error:
```js
=> Meteor server restarted
I20151115-21:16:47.198(1)? Internal server error in publications/agency [TypeError: Object [object Object] has no method 'apply'] TypeError: Object [object Object] has no method 'apply'
I20151115-21:16:47.199(1)?     at Meteor.publish (packages/simple_rest/packages/simple_rest.js:170:1)
I20151115-21:16:47.199(1)?     at catchAndReportErrors (packages/simple_rest/packages/simple_rest.js:372:1)
I20151115-21:16:47.199(1)?     at Meteor.publish (packages/simple_rest/packages/simple_rest.js:156:1)
I20151115-21:16:47.199(1)?     at JsonRoutes.add (packages/simple_json-routes/packages/simple_json-routes.js:53:1)
```

What am I doing wrong?

http://localhost:3000/publications/api-routes works and returns this:
```js
{
  "api-routes": [
    {
      "_id": "/publications/api-routes",
      "methods": [
        "get"
      ],
      "path": "/publications/api-routes"
    },
    {
      "_id": "/publications/meteor_autoupdate_clientVersions",
      "methods": [
        "get"
      ],
      "path": "/publications/meteor_autoupdate_clientVersions"
    },
    {
      "_id": "/agency",
      "methods": [
        "options",
        "post"
      ],
      "path": "/agency"
    },
    {
      "_id": "/agency/:_id",
      "methods": [
        "options",
        "patch",
        "options",
        "delete"
      ],
      "path": "/agency/:_id"
    },
    {
      "_id": "/publications/agency",
      "methods": [
        "get"
      ],
      "path": "/publications/agency"
    }
  ]
}
```

**Comment by dotnetwise** [comment]
My mistake!! I have omitted the `publish func` entirely
