### ISSUE TITLE
Publish array fails - method fetch not found

### ISSUE THREAD

**Issue by dotnetwise** [stubailo/meteor-rest#80]
If you publish an `array` it should just work (don't always expect to return a `cursor`). Currently it fails - 'object has no method 'fetch'`

```js
 Internal server error in /logs/:0 [TypeError: Object [object Object] has no method 'fetch'] TypeError: Object [object Object] has no method 'fetch'
at httpPublishCursor (packages/simple_rest/packages/simple_rest.js:292:1)
at Meteor.publish (packages/simple_rest/packages/simple_rest.js:181:1)
at Array.forEach (native)
at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
at Meteor.publish (packages/simple_rest/packages/simple_rest.js:180:1)
at catchAndReportErrors (packages/simple_rest/packages/simple_rest.js:372:1)
at Meteor.publish (packages/simple_rest/packages/simple_rest.js:156:1)
at JsonRoutes.add (packages/simple_json-routes/packages/simple_json-routes.js:53:1)
```

**Comment by stubailo** [comment]
Really, in DDP you can just return an array of documents? I don't think that's the case, but I'll go check..

**Comment by stubailo** [comment]
Yeah here's what I get if I publish an array of documents:

```js
I20160106-09:52:19.315(-8)? Exception from sub array id kXPEhcfYpvmDA4d8c Error: Publish function returned an array of non-Cursors
I20160106-09:52:19.315(-8)?     at [object Object]._.extend._publishHandlerResult (livedata_server.js:1076:20)
I20160106-09:52:19.315(-8)?     at [object Object]._.extend._runHandler (livedata_server.js:1038:10)
I20160106-09:52:19.316(-8)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20160106-09:52:19.316(-8)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20160106-09:52:19.316(-8)?     at livedata_server.js:548:43
```

Or maybe you're referring to returning an array of cursors? Let me see about that

**Comment by stubailo** [comment]
No, that should work too. I'm not really sure what you're looking for here.

**Comment by dotnetwise** [comment]
No simply an array

```js
Meteor.publish('logs', function (keys) {
return [{x:1}, {y:2}, {z:3}];
}, {
    url: '/logs',
    httpMethod: "get",
});

**Comment by stubailo** [comment]
I think the intention of this package is to allow you to access your Meteor publications and methods over HTTP, and that isn't a valid Meteor publication.

If you just want to have a convenient HTTP endpoint, use [JsonRoutes](https://github.com/stubailo/meteor-rest/tree/devel/packages/json-routes), the package simple:rest is based on:

```js
JsonRoutes.add("get", "/logs", function (req, res, next) {
  JsonRoutes.sendResult(res, {
    data: [{x:1}, {y:2}, {z:3}];
  });
});
```

**Comment by dotnetwise** [comment]
The problem with that is that is static data.

However I moved from a `collection` with `Meteor.publish` to `Meteor.method` which seems to be working just fine.
Basically is transparent to the rest world, either is a collection or a server method.

**Comment by dotnetwise** [comment]
Btw, how do you disable "nice json formatting" ?

**Comment by stubailo** [comment]
Here it is with dynamic data:

```js
JsonRoutes.add("get", "/logs", function (req, res, next) {
  JsonRoutes.sendResult(res, {
    data: MyCollection.find().fetch();
  });
});
```

Currently there is no option to disable JSON formatting, but if you are using HTTP compression it shouldn't matter at all since the extra space will be compressed away. I could accept a PR to add such an option to `JsonRoutes.sendResult`.

**Comment by dotnetwise** [comment]
That one is useless by default. Chrome will know to arrange your json anyways (or the `jsonview` plugin). So perhaps it should be turned off by default, or by whether you are in debug mode or not.

**Comment by stubailo** [comment]
It's useful if you are testing something from the terminal with curl, for example. My point is more that it doesn't actually matter if it's formatted or not.

**Comment by dotnetwise** [comment]
So could be formatted only if debugging i.e. `meteor run`

**Comment by stubailo** [comment]
Sounds like a good plan - is there a good way of determining if we are in debug mode? I heard @maxsavin has some package

**Comment by dotnetwise** [comment]
You said about `gzip` - is there any package for that, or does `simple-rest` how to do it?

**Comment by nooitaf** [comment]
I would prefer an option, and like to serve readable json.

Isn't compression done by nginx/apache?

**Comment by dotnetwise** [comment]
Only if your meteor is behind `ngix/apache`. What if it is not?

Could this be part of the options? e.g. implement gzipping that is allready supported in node.js 
http://stackoverflow.com/questions/24052538/using-gzip-in-meteor

**Comment by nooitaf** [comment]
Afaik, as soon as you implement ssl/https you will need something in front of meteor anyways. 

As your link states, meteor seems to compress json bij default and can be configured to compress more, but it seems to be more global.

You could also have a look at [Restivus](https://github.com/kahmali/meteor-restivus), it has a prettyJson option and you can just return an array or such.

**Comment by nooitaf** [comment]
Hmm [JsonRoutes](https://github.com/stubailo/meteor-rest/tree/devel/packages/json-routes) already reacts to an evironment variable 

```javascript
/* The JSON response will be pretty printed if NODE_ENV is `development`.*/
function writeJsonToBody(res, json) {
  if (json !== undefined) {
    var shouldPrettyPrint = (process.env.NODE_ENV === 'development');
    var spacer = shouldPrettyPrint ? 2 : null;
    res.setHeader('Content-type', 'application/json');
    res.write(JSON.stringify(json, null, spacer));
  }
}
```
https://github.com/stubailo/meteor-rest/blob/devel/packages/json-routes/json-routes.js#L118

**Comment by dotnetwise** [comment]
That is true. If you run with `--production` flag it does already `gzip` the response!
However `process.env.NODE_ENV === 'development'` is still true

**Comment by dotnetwise** [comment]
Perhaps is not the right place to ask - but is there a way you can control the cache headers from a server method?

**Comment by stubailo** [comment]
Hmm, currently the options to `Meteor.method` don't let you set the headers, but that could be easily added since `JsonRoutes` supports it.

**Comment by dotnetwise** [comment]
how?

**Comment by stubailo** [comment]
You could PR `Meteor.method` to take an option `headers`, that is later passed to `JsonRoutes.add`. This would be in `packages/rest/rest.js`
